services:
  eureka:
    container_name: EUREKASERVER
    build:
      context:
      dockerfile: C:\Faculdade\MICROSSERVIÇOS JAVA\Desenvolvimento de Serviços com Spring Boot\AssessmentJava\eureka-service\Docker
